[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
